on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 109.234.164.181
          server-dir: /public_html/mediatekformation/
          username: habu7760
          password: ${{ secrets.ftp_password }}
